### ISSUE TITLE
Cannot find file when trying to run 

### ISSUE THREAD

**Issue by sc30301** [xliu-uth/ImmClassifier#4]
Hello, 

After pulling the docker container I am trying to run the command but am consistently getting "Error in main() : Cannot find file", even when specifying the correct input path using:

docker run --volume ${PWD:``[/tmp``]} -ti sgosline/imm-classifier --input "test.txt"

Any help would be much appreciated.

**Comment by xliu-uth** [comment]
Hi,
Thank you for trying out ImmClassifier! Is text.txt under your local directory where you initiated docker run?

**Comment by sc30301** [comment]
Yes it is.

**Comment by xliu-uth** [comment]
Hi,
Could you check if the docker container is mounted well and the C drive is shared to docker? Thank you!

Here's an example
https://dev.to/bogicevic7/windows-docker-shared-volume-folder-46d1
