### ISSUE TITLE
Question about running with rds input

### ISSUE THREAD

**Issue by s2hui** [xliu-uth/ImmClassifier#7]
Hello,

I just started using your package and had a question about running the software with rds input.

I did as the documentation said:
* Loaded my matrix as log2CPM into a data.frame with cells as rows and genes a columns
* Saved my data.frame as rds object using saveRDS()

When I run the docker:

`docker run --volume /Users/shui/out:/tmp --volume /Users/shui/data:/app -ti xliu18/imm-classifier --input /app/CPM_dataframe.rds --output pred_labels`

This is the output:

`Loading required package: ImmClassifier
`

And then the package terminates.  I have no idea what the problem is and was hoping to get some insight on what to do.
My matrix is around 33K genes and 48K cells.

Thank you

**Comment by xliu-uth** [comment]
Hi, how much memory have you allocated for docker?

**Comment by xliu-uth** [comment]
Hi, this step is the most time-consuming step because the number of cells in this reference dataset is huge (~70k cells). Please give ImmClassifier a few minutes to finish step.  Please let me know if it is unexpectedly stopped or it takes longer than 1 hour.  Once this step is done, the rest steps are much faster.

**Comment by s2hui** [comment]
It's been running for over an hour. 

A few more details, I converted the docker image to singularity so I could run on our HPC cluster.  As you said, the dataset is large so this is more likely the reason it is taking so long, but I thought I would mention it anyways.

Thanks for your help.

**Comment by xliu-uth** [comment]
Thank you for letting me know! Hope it is done now.

**Comment by s2hui** [comment]
Hi,  The package passed the training step (over an hour) and generated the dnn.input.txt file but ended in error bc it couldn't find the pandas module.    I am wondering why this is happening (I thought this module would be in the docker) and how to resolve this.
thank you!

```
[1] "Write concanetated probabilities to /tmp/Lymphocytes.dnn.input.txt"
Error in py_run_file_impl(file, local, convert) : 
  ModuleNotFoundError: No module named 'pandas'

Detailed traceback: 
  File "<string>", line 1, in <module>
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 24, in _import_hook
    level=level
Calls: main ... predictHierarchy -> source_python -> py_run_file -> py_run_file_impl
Execution halted
```

**Comment by s2hui** [comment]
I ran the package as a Docker on a local VM as your documentation says and it executed and outputted correctly.  So the error (could not find pandas module) is prob due to trying to run it via singularity on the cluster.

thank you

**Comment by jefftc** [comment]
Sometimes the environment variables in Docker aren't set correctly in Singularity.  Xuan, where is pandas installed in the container?  Perhaps setting the PYTHON_PATH variable before or while running ImmClassifier in singularity will help to solve the problem.

Jeff

**Comment by xliu-uth** [comment]
The pandas is installed to /usr/local/lib/python3.8/dist-packages.

**Comment by xliu-uth** [comment]
Hi,
The tensorflow error looks harmless unless you would like to utilize GPU. I have seen the same error message when I tested ImmClassifier on a laptop without GPU and ImmClassifier was able to use CPU to finish the prediction. From the output msg, it looks to me that ImmClassifier was in the middle of prediction. Could you please let me know what happened after you see the output msg? Was ImmClassifier still running or it was stopped? 

Thanks!


> I ran the package as a Docker on a local VM and it executed without giving the `ModuleNotFoundError`, but I get the following output/error now related to tensorflow it seems. The final output file (ie output_prefix.output.txt) is not created/written:
> 
> ```
> 2021-03-16 03:43:00.422433: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib:/usr/local/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-11-openjdk-amd64/lib/server
> 2021-03-16 03:43:00.422480: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> load query file /tmp/Lymphocytes.dnn.input.txt
> perform normalization
> load pre-trained dnn models
> 2021-03-16 03:43:05.109079: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
> 2021-03-16 03:43:05.109453: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib:/usr/local/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-11-openjdk-amd64/lib/server
> 2021-03-16 03:43:05.109474: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
> 2021-03-16 03:43:05.109504: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (7efbb88bdd04): /proc/driver/nvidia/version does not exist
> 2021-03-16 03:43:05.109763: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2021-03-16 03:43:05.111044: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
> predict query dataset using dnn models
> 2021-03-16 03:43:06.094538: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
> 2021-03-16 03:43:06.095046: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2599995000 Hz
> ```
> 
> thank you

**Comment by s2hui** [comment]
The messages immediately following the tensorflow output are below and the program finishes.

```
save results to disk
Loading required package: data.table

Attaching package: ‘data.table’

The following objects are masked from ‘package:dplyr’:

    between, first, last

[1] "Read /tmp/Lymphocytes.deeplearning.ontotree.stats.txt"
[1] "Assign the final labels"
[1] "Finish assigning the final labels"
[1] "/tmp/Lymphocytes.output.txt"
```

In the output directory I see the following:

```
-rw-r--r--  1 root root  74M Mar 15 23:43 Lymphocytes.deeplearning.ontotree.stats.txt
-rw-r--r--  1 root root  46M Mar 15 23:42 Lymphocytes.dnn.input.txt
-rw-r--r--  1 root root  35M Mar 15 23:44 Lymphocytes.output.txt
drwxr-xr-x  2 root root 4.0K Mar 15 23:43 __pycache__
-rw-r--r--  1 shui shui    0 Mar 15 22:28 .sudo_as_admin_successful
-rw-------  1 root root  940 Mar 15 23:43 tmpcvp666bv.py

```

**Comment by jefftc** [comment]
Hmmm...  Python should be able to find it here.  How is python being called?  It's possible that in Singularity, the wrong python is being called, and we need to force it to call the one installed with the container.

Jeff

**Comment by s2hui** [comment]
Thanks, I'll see if addressing those suggestions help when running on the cluster (i.e .explicitly setting PYTHON_PATH and forcing the proper version of python to be used).

Currently, I have it running on the local VM as a docker (not singularity), except it doesn't output the final output file (ie output_prefix.output.txt).  Thanks for your help!

**Comment by xliu-uth** [comment]
Hi,
Thank you for the information. From the output message, the output file is Lymphocytes.output.txt. 

> The messages immediately following the tensorflow output are below and the program finishes.
> 
> ```
> save results to disk
> Loading required package: data.table
> 
> Attaching package: ‘data.table’
> 
> The following objects are masked from ‘package:dplyr’:
> 
>     between, first, last
> 
> [1] "Read /tmp/Lymphocytes.deeplearning.ontotree.stats.txt"
> [1] "Assign the final labels"
> [1] "Finish assigning the final labels"
> [1] "/tmp/Lymphocytes.output.txt"
> ```
> 
> In the output directory I see the following:
> 
> ```
> -rw-r--r--  1 root root  74M Mar 15 23:43 Lymphocytes.deeplearning.ontotree.stats.txt
> -rw-r--r--  1 root root  46M Mar 15 23:42 Lymphocytes.dnn.input.txt
> -rw-r--r--  1 root root  35M Mar 15 23:44 Lymphocytes.output.txt
> drwxr-xr-x  2 root root 4.0K Mar 15 23:43 __pycache__
> -rw-r--r--  1 shui shui    0 Mar 15 22:28 .sudo_as_admin_successful
> -rw-------  1 root root  940 Mar 15 23:43 tmpcvp666bv.py
> ```

**Comment by s2hui** [comment]
Thanks yes I do see the file, however I was expecting the contents to be like the following:

https://github.com/xliu-uth/ImmClassifier/blob/master/output/bulk.output.txt

But instead it looks to be a matrix with probabilities in it.

![image](https://user-images.githubusercontent.com/10944134/111346691-d989e580-8654-11eb-852a-f6e82e10b765.png)

**Comment by s2hui** [comment]
Thank you, sorry about the oversight.  I was confused bc the format of the output file was not the same as (ie two columns where the second is the predicted label):

https://github.com/xliu-uth/ImmClassifier/blob/master/output/bulk.output.txt

The contents of output.txt is a matrix of what looks like probabilities.  But when I look at it closer it, the first two columns of this matrix are indeed the barcodes and the predicted label.

Thanks for your help!

**Comment by xliu-uth** [comment]
Sorry for the confusion and thank you for letting me know. I will update the example file.
