### ISSUE TITLE
Program terminates with no prediction output

### ISSUE THREAD

**Issue by s2hui** [xliu-uth/ImmClassifier#8]
Hello,

I am new to ImmClassifier and I am running into some issues. 

I ran the docker using input (log2CPM) formatted as per the doc (genes as rows, cells as cols):

`docker run --volume /Users/shui/out:/tmp --volume /Users/shui/data:/app -ti xliu18/imm-classifier --input /app/CPM_1-100.txt --output pred_labels`

The output is below and no output file is created.   I am guessing an error occured?

My input file is a tab delimited file with 30K genes and 100 cells.

Thanks for your help!

```
Loading required package: ImmClassifier
[1] "Open query file /app/Lymphocytes-res0.4-pcs16-CPM_dataframe-1-100.txt"
[1] "reshape input file"
[1] "convert to data.frame"
[1] "Query file input is done"
[1] "Training a classifier from Ref1: The Human Cell Atlas bone marrow single-cell interactive web portal"
Loading required package: dplyr

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Loading required package: sva
Loading required package: mgcv
Loading required package: nlme

Attaching package: ‘nlme’

The following object is masked from ‘package:dplyr’:

    collapse

This is mgcv 1.8-33. For overview type 'help("mgcv-package")'.
Loading required package: genefilter
Loading required package: BiocParallel
[1] "load train/test partition from training set /ImmClassifier/data/hca-bm-train-test-dat.rds"
[1] "Feature reduced from # 1127 to 1107"
[1] "Extract features" 
```

**Comment by xliu-uth** [comment]
Hi, how much memory have you allocated for docker? Could you increase it to 8G or more?

**Comment by s2hui** [comment]
Thanks I have increased the memory as you instructed and it is now progressing beyond "Extracting features".
